development:
  username: webapp
  password: rails
  adapter: mysql2
  encoding: utf8
  database: user_tags
  pool: 5
  timeout: 5000

test:
  username: webapp
  password: rails
  adapter: mysql2
  encoding: utf8
  database: test_user_tags
  pool: 5
  timeout: 5000